import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';
import styles from './layout.module.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<header className={styles.header}>
					<h1>Demo Note</h1>
					<nav className={styles.nav}>
						<h1>
							<Link href='/'>Home</Link>
						</h1>
						<Link href='/contact'>Contact</Link>
						<Link href='/about'>About</Link>
					</nav>
				</header>
				{children}
			</body>
		</html>
	);
}
